### ISSUE TITLE
在nuxt中获取vue-markdown-loader对象

### ISSUE THREAD

**Issue by cellargalaxy** [tianyong90/vue-markdown-loader#2]
* 我使用nuxt进行博客的开发。我需要怎样在nuxt里进行配置才能使用vue-markdown-loader呢？
* 我能获取一个vue-markdown-loader的对象（如果有），以能够动态渲染一个markdown文本或者文件吗？如果可以，我应当怎样做呢？

感谢

**Comment by tianyong90** [comment]
@cellargalaxy  https://github.com/tianyong90/blog 可以参考我博客的配置，开源的。vue-markdown-loader readme 忘了更新了，找空我再补上。

**Comment by cellargalaxy** [comment]
那怎样才能获取到用于渲染markdown的对象呢

我看https://github.com/tianyong90/blog理解到的做法是，在nuxt.config.ts配置扫描posts目录下的md文件，在_slug.vue里就直接返回html了
